version: 0.2

phases:
  build:
    commands:
      - mvn clean install -P prod

artifacts:
  files:
    - integration/prod/appspec.yml
    - integration/prod/scripts/*
    - target/okky-notification-1.0.0.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'