version: 0.2

phases:
  build:
    commands:
      - aws s3 cp s3://okky-config/settings.xml /root/.m2/settings.xml
      - mvn clean install -P prod

artifacts:
  files:
    - integration/prod/appspec.yml
    - integration/prod/scripts/*
    - target/okky-notification-1.0.0.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'