version: 0.2

env:
  parameter-store:
    SONAR_LOGIN: "/okky/codebuild/sonar.login"

phases:
  build:
    commands:
      - aws s3 cp s3://config-okky-stg/settings.xml /root/.m2/settings.xml
      - mvn clean install sonar:sonar -P stg -Dsonar.login=$SONAR_LOGIN

artifacts:
  files:
    - integration/stg/appspec.yml
    - integration/stg/scripts/*
    - target/okky-notification-1.0.0.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'